add custom payload test doc
jim-minter/rp pull request #10
Opened 2019-11-25 18:12 UTC by mjudeikis

Add write-up about payload testing

2019-11-25 19:03 UTC, jim-minter requested changes

2019-11-25 19:03 UTC, jim-minter commented on docs/Development.md
> +OpenShift v4 uses a release payload image to configure the cluster. Sometimes we need to test custom payload before we submit a patch to upstream. This section describes how to do this.
please set your editor to wrap to 80, and wrap to 80 on all .md files.

2019-11-25 19:03 UTC, jim-minter commented on docs/Development.md
> +# Custom payload testing
call the file custom-payload-testing.md

2019-11-26 09:21 UTC, mjudeikis commented
done

2019-11-28 02:40 UTC, merged