Middleware tests
jim-minter/rp pull request #45
Opened 2019-12-10 12:40 UTC by mjudeikis

Simple Middleware tests

@jim-minter wdyt if to add something similar for all Middlewares?

2019-12-11 05:32 UTC, asalkeld commented on pkg/frontend/middleware/body_test.go
> +
any reason for these newlines? just seems to take up more space

2019-12-11 14:03 UTC, jim-minter requested changes

2019-12-11 14:03 UTC, jim-minter commented on pkg/frontend/middleware/body_test.go
> +	"github.com/stretchr/testify/assert"
I'm not prepared to bring this library in right now.  We're doing fine in unit tests without it.  If we end up pulling in Ginkgo for e2es, we'll end up pulling in Gomega as well.  I'd rather not use any assertion library.  Also if we decide to use one in unit tests, we should also standardise on using it everywhere.

TL;DR: for now, please just do
```
if err != nil {
	t.Fatal(err)
}
```

2019-12-11 14:03 UTC, jim-minter commented on pkg/frontend/middleware/body_test.go
> +			method: "GET",
http.MethodGet etc

2019-12-11 14:03 UTC, jim-minter commented on pkg/frontend/middleware/body_test.go
> +			expectedCode: 200,
http.StatusOK etc

2019-12-11 14:03 UTC, jim-minter commented on pkg/frontend/middleware/body_test.go
> +	ts := httptest.NewServer(Body(GetTestHandler()))
didn't know this existed, I wonder if it simplifies my security_test.go.  Will look :-)

2019-12-11 14:03 UTC, jim-minter commented on pkg/frontend/middleware/body_test.go
> +		expectedCode int
wantStatusCode - we're standardising on want

2019-12-11 14:03 UTC, jim-minter commented on pkg/frontend/middleware/body_test.go
> +		header map[string]string
http.Header

2019-12-11 14:03 UTC, jim-minter commented on pkg/frontend/middleware/body_test.go
> +	client := http.Client{}
use http.DefaultClient below instead

2019-12-11 14:03 UTC, jim-minter commented on pkg/frontend/middleware/body_test.go
> +			var u bytes.Buffer
I believe this is not needed with httptest?

2019-12-11 14:03 UTC, jim-minter commented on pkg/frontend/middleware/body_test.go
> +			res, err := client.Do(req)
resp

2019-12-11 14:03 UTC, jim-minter commented on pkg/frontend/middleware/body_test.go
> +			assert.NoError(err)
always find a way to make sure you do a resp.Body.Close() after making an http request

2019-12-11 14:03 UTC, jim-minter commented on pkg/frontend/middleware/body_test.go
> +func GetTestHandler() http.HandlerFunc {
this just boils down to `http.HandlerFunc(func(http.ResponseWriter, *http.Request) {})`

2019-12-11 14:03 UTC, jim-minter commented on pkg/frontend/middleware/body_test.go
> +			header: map[string]string{
hint, this will become http.Header{"Content-Type": []string{"test"}},

2019-12-11 14:04 UTC, jim-minter commented
> @jim-minter wdyt if to add something similar for all Middlewares?

Yes please - that's why I broke them out into a different package / files :-)

2019-12-11 15:07 UTC, mjudeikis commented on pkg/frontend/middleware/body_test.go
> +	ts := httptest.NewServer(Body(GetTestHandler()))
I rewrote this even more. more will follow.

2019-12-11 15:08 UTC, mjudeikis commented on pkg/frontend/middleware/body_test.go
> +	client := http.Client{}
removed overall

2019-12-11 15:08 UTC, mjudeikis commented on pkg/frontend/middleware/body_test.go
> +			var u bytes.Buffer
removed.

2019-12-16 19:33 UTC, jim-minter commented
merged - this was OK, but it could really have been much more rigorous - please see the subsequent fixup commit and consider this when implementing the remaining middleware functions :-)

2019-12-16 19:33 UTC, closed without merging