Adds tests for ARM clientauthoriser
jim-minter/rp pull request #46
Opened 2019-12-10 16:33 UTC by m1kola

2019-12-11 14:16 UTC, jim-minter requested changes
looks good, just nits

2019-12-11 14:16 UTC, jim-minter commented on pkg/util/clientauthorizer/arm_test.go
> +	t.Run("IsReady", func(t *testing.T) {
make these separate top level level `func TestFoo`s please

2019-12-11 14:16 UTC, jim-minter commented on pkg/util/clientauthorizer/arm_test.go
> +			want bool
I think this would be better to be reversed, i.e. wantErr string

2019-12-11 15:58 UTC, m1kola commented
@jim-minter PTAL, I updated and rebased on top of the master.

2019-12-16 21:15 UTC, jim-minter commented
merged, thanks

2019-12-16 21:15 UTC, closed without merging